Session2
KojoBarbie/flutter-training-yumemi pull request #15
Opened 2024-07-12 13:53 UTC by KojoBarbie

## 課題

close #3 

## 対応箇所

- [ ] 天気の画像がreloadを押すたびに表示されるようにした。

## 動作

https://gyazo.com/713f20dc0425d737a1ff49fcc0f24def

2024-07-12 15:18 UTC, okt4hei requested changes
1点だけお願いします！

2024-07-12 15:18 UTC, okt4hei commented on lib/yumemi_weather_repository.dart
> +      throw Exception('予期しないエラーが発生しました。');
catch的な部分でExceptionをthrowするときはrethrowを使うのが良いっぽいです（スタックトレース的に）
https://zenn.dev/iwaku/articles/2020-12-19-iwaku

2024-07-17 09:36 UTC, KojoBarbie commented
@okt4hei 
修正しました！

2024-07-18 06:47 UTC, okt4hei approved these changes
LGTM!

2024-07-18 07:56 UTC, merged